dist: xenial
language: python
services:
  - postgresql
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - py.test --cov-report term-missing --cov app -v
deploy:
  provider: heroku
  api_key:
    secure: "8914777b-9c4b-4037-b10d-35e0322b8633"
  app: sos-shoppingcart
