dist: xenial
language: python
services:
  - postgresql
python:
  - "3.7"
cache: pip
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest-flask
script:
  - git clone https://github.com/teeratton/sos-shoppingcart.git
  - cd sos-shoppingcart
  - coverage run –source=src
  - coverage report
after_success:
  - codecov
deploy:
  provider: heroku
  api_key:
    secure: 8914777b-9c4b-4037-b10d-35e0322b8633
  app: sos-shoppingcart
